### ISSUE TITLE
Clarify / Reword SRE spec

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/spec#21]
Does this SLO example contradict itself?

https://github.com/keptn/spec/blob/0.1.2/sre.md#service-level-indicators-sli-configuration

```
comparison:
  compare_with: "single_result"
  include_result_with_score: "pass"
  number_of_comparison_results: 3
  aggregate_function: avg
```

> This comparison configuration means that the current result is only compared to the last result that passed.

Doesn't the `compare_with: "single_result"` actually negate the `number_of_comparison_results`?

Perhaps the example should be:
```
comparison:
  compare_with: "single_result"
  include_result_with_score: "pass"
  aggregate_function: avg
```
