### ISSUE TITLE
Keptn Shipyard: Update specification for deployment- and test-strategy

### ISSUE THREAD

**Issue by GustavAT** [keptn/spec#58]
The specification documentation still uses the property `strategy` for the deployment- and test-strategy. It should be `deploymentstrategy` and `teststrategy`.

Failing example:
```yaml
- name: deployment
  properties:
    strategy: direct
```
should be
```yaml
- name: deployment
  properties:
    deploymentstrategy: direct
```
