### ISSUE TITLE
Documentation of stage events

### ISSUE THREAD

**Issue by johannes-b** [keptn/spec#62]
In the https://github.com/keptn/spec/blob/master/cloudevents.md a section should be provided to explain the stage events fired by the shipyard-controller. Given the below example of a shipyard, the following stage events are fired: 

* `sh.keptn.event.dev.artifact-delivery.triggered`
* `sh.keptn.event.dev.artifact-delivery.finished`
* `sh.keptn.event.staging.artifact-delivery.triggered`
* `sh.keptn.event.staging.artifact-delivery.finished`

```
apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-sockshop"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "artifact-delivery"
          tasks:
            - name: "deployment"
            - name: "test"
            - name: "evaluation"
            - name: "release"

    - name: "staging"
      sequences:
        - name: "artifact-delivery"
          triggers:
            - "dev.artifact-delivery.finished"
          tasks:
            - name: "deployment"
            - name: "test"
            - name: "evaluation"
            - name: "release"
``` 

**Task:** Provide documentation to explain:
* The pattern of a stage event follows this format: sh.keptn.event.{stage}.{seqeunece}.{triggered | finished}
* The `result`, `status`, and `message` properties represent the properties from the last successfully executed task in the sequence.
