### ISSUE TITLE
Resolve differences between properties and "special terms" like "triggeredOn" and "triggeredAfter"

### ISSUE THREAD

**Issue by agardnerIT** [keptn/spec#93]
task properties are denotes as:

```
- name: "task1"
  properties:
    foo: bar
```

A task can be "triggered after" a certain amount of time like this:
```
- name: "task1"
  triggeredAfter: 10m
```

Why the difference? Why not streamline and list as just another property:

```
- name: "task1"
  properties:
    foo: bar
    triggeredAfter: 10m
```

Same idea for sequences being "triggered on" other events. Currently the syntax is:

```
- name: sequence1
  triggeredOn:
    - event: "dev.delivery.finished"
```

Why not:

```
- name: sequence1
  properties:
    triggeredOn:
      event: dev.delivery.finished
```
