### ISSUE TITLE
Is Keptn following the spec?

### ISSUE THREAD

**Issue by lmmarsano** [keptn/spec#94]
In v0.15.0, I'm getting [breaking](https://keptn.sh/docs/news/release_announcements/keptn-0150/#breaking-changes) validation errors.
```yaml
name: invalid response
shortmsg: |-
  properties: /data/events/0/data/evaluation/indicatorResults/0/value/comparedValue: must NOT have additional properties
  properties: /data/events/0/data/evaluation/indicatorResults/1/value/comparedValue: must NOT have additional properties
  properties: /data/events/0/data/evaluation: must have property 'gitCommit'
info:
  request:
    baseURL: https://[REDACTED]/api/
    headers:
      x-token: ***
    method: GET
    url: mongodb-datastore/event
    params:
      type: sh.keptn.event.evaluation.finished
      keptnContext: b204cf07-5973-470a-8f63-7e44e1bd4d35
  response:
    status: 200
    statusText: OK
    headers:
      server: istio-envoy
      date: Sat, 14 May 2022 17:34:30 GMT
      content-type: application/json
      x-envoy-upstream-service-time: '11'
      transfer-encoding: chunked
    data:
      events:
      - data:
          evaluation:
            indicatorResults:
            - displayName: ''
              keySli: true
              passTargets:
              - criteria: <2000
                targetValue: 2000
                violated: false
              score: 20
              status: pass
              value:
                comparedValue: 0
                metric: avg_responsetime
                success: true
                value: 1.5889433962264152
              warningTargets:
              - criteria: <1000
                targetValue: 1000
                violated: false
            - displayName: ''
              keySli: true
              passTargets:
              - criteria: <1
                targetValue: 1
                violated: false
              score: 20
              status: pass
              value:
                comparedValue: 0
                metric: error_rate
                success: true
                value: 0
              warningTargets:
              - criteria: <2
                targetValue: 2
                violated: false
            result: pass
            score: 100
            sloFileContent: c3BlY192ZXJzaW9uOiAnMS4wJwpvYmplY3RpdmVzOgotIHNsaTogYXZnX3Jlc3BvbnNldGltZQogIHBhc3M6CiAgLSBjcml0ZXJpYToKICAgIC0gPDIwMDAKICB3YXJuaW5nOgogIC0gY3JpdGVyaWE6CiAgICAtIDwxMDAwCiAgd2VpZ2h0OiAyMAogIGtleV9zbGk6IHRydWUKLSBzbGk6IGVycm9yX3JhdGUKICBwYXNzOgogIC0gY3JpdGVyaWE6CiAgICAtIDwxCiAgd2FybmluZzoKICAtIGNyaXRlcmlhOgogICAgLSA8MgogIHdlaWdodDogMjAKICBrZXlfc2xpOiB0cnVlCnRvdGFsX3Njb3JlOgogIHBhc3M6IDkwJQogIHdhcm5pbmc6IDYwJQpjb21wYXJpc29uOgogIGNvbXBhcmVfd2l0aDogc2V2ZXJhbF9yZXN1bHRzCiAgaW5jbHVkZV9yZXN1bHRfd2l0aF9zY29yZTogcGFzc19vcl93YXJuCiAgbnVtYmVyX29mX2NvbXBhcmlzb25fcmVzdWx0czogMQo=
            timeEnd: '2022-05-14T17:31:04.360Z'
            timeStart: '2022-05-14T17:30:04.360Z'
          labels:
            DtCreds: dynatrace-np
            appServiceId: appsvc0
            buildId: '20115'
            definition: EMF.Keptn.Sandbox
            dtEntityName0: EMFSandbox_Blue
            dtEntityWebUrl0: https://[REDACTED]/e/54d139b9-23ee-466d-ad7a-f98e0bd8bdf4/ui/nav/SERVICE-A5D15D718DF71792
            pipeline: https://dev.azure.com/[REDACTED]/6b945a9d-1349-4d3c-9858-0b57fcad3e9e/_build/results?buildId=20115
            runby: Microsoft.VisualStudio.Services.TFS
          project: devops
          result: pass
          service: emf.keptn.sandbox
          stage: stage
          status: succeeded
        id: 6c3b309f-91b0-4ae0-92b8-c789537b7101
        shkeptncontext: b204cf07-5973-470a-8f63-7e44e1bd4d35
        shkeptnspecversion: 0.2.4
        source: lighthouse-service
        specversion: '1.0'
        time: '2022-05-14T17:33:04.769Z'
        triggeredid: 1126c26a-d70d-48ee-be37-c04df27c6016
        type: sh.keptn.event.evaluation.finished
      pageSize: 20
      totalCount: 1
  errors:
  - instancePath: /data/events/0/data/evaluation/indicatorResults/0/value/comparedValue
    schemaPath: /definitions/indicatorResult/properties/value
    keyword: properties
    params:
      error: additional
      additionalProperty: comparedValue
    message: must NOT have additional properties
  - instancePath: /data/events/0/data/evaluation/indicatorResults/1/value/comparedValue
    schemaPath: /definitions/indicatorResult/properties/value
    keyword: properties
    params:
      error: additional
      additionalProperty: comparedValue
    message: must NOT have additional properties
  - instancePath: /data/events/0/data/evaluation
    schemaPath: /definitions/evaluation/properties/gitCommit
    keyword: properties
    params:
      error: missing
      missingProperty: gitCommit
    message: must have property 'gitCommit'
```

These PRs seem to conflict with schema lines.
- keptn/go-utils#430
    https://github.com/keptn/spec/blob/f6f1e1f33937a7463ca1a4b23a6977fecc696696/cloudevents.md?plain=1#L30
- keptn/go-utils#358
    https://github.com/keptn/spec/blob/f6f1e1f33937a7463ca1a4b23a6977fecc696696/cloudevents.md?plain=1#L2769

Could CI/CD check for compatibility breaks between design & generated schemas?
There are various tools to do that:
- https://github.com/tufin/oasdiff
- https://github.com/OpenAPITools/openapi-diff
- https://bitbucket.org/atlassian/openapi-diff
